# Generated by Django 2.2.8 on 2020-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200828_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'danger'), ('S', 'seconary'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
