# Generated by Django 2.2.8 on 2020-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200828_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='printful_item_variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Posters'), ('M', 'Mugs'), ('C', 'Clothing')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'danger'), ('P', 'primary'), ('S', 'seconary')], max_length=1, null=True),
        ),
    ]
