# Generated by Django 2.2.8 on 2020-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200917_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintree_transaction_id',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'shipping'), ('B', 'billing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('C', 'Clothing'), ('P', 'Posters'), ('M', 'Mugs')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'seconary'), ('P', 'primary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
