# Generated by Django 2.2.8 on 2020-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200831_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'shipping'), ('B', 'billing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Posters'), ('C', 'Clothing'), ('M', 'Mugs')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'danger'), ('S', 'seconary'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
