# Generated by Django 2.2.8 on 2020-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200917_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='donation_added',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('C', 'Clothing'), ('P', 'Posters'), ('M', 'Mugs')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'danger'), ('P', 'primary'), ('S', 'seconary')], max_length=1, null=True),
        ),
    ]
