# Generated by Django 2.2.8 on 2020-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200908_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mugs'), ('C', 'Clothing'), ('P', 'Posters')], max_length=2, null=True),
        ),
    ]
