# Generated by Django 2.2.8 on 2020-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200917_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'seconary'), ('D', 'danger'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
