# Generated by Django 2.2.8 on 2020-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200917_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mugs'), ('P', 'Posters'), ('C', 'Clothing')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'seconary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
