# Generated by Django 2.2.8 on 2020-09-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200917_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mugs'), ('C', 'Clothing'), ('P', 'Posters'), ('T', 'Tip')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'danger'), ('S', 'seconary'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
